# Generated by Django 4.0.3 on 2022-03-24 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField(default='', max_length=500)),
                ('destination', models.TextField(default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_estimates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
