# Generated by Django 4.0.3 on 2022-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0002_savedestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedestimate',
            name='miles',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
