# Generated by Django 4.0.3 on 2022-03-25 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0003_savedestimate_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedestimate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
