# Generated by Django 4.0.3 on 2022-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0004_savedestimate_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedestimate',
            name='destination_formatted',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='savedestimate',
            name='origin_formatted',
            field=models.TextField(default=''),
        ),
    ]
